openapi: 3.0.1
info:
  title: Book Store
  description: Assignment
  termsOfService: Please adhere to policies
  version: "1.0"
servers:
- url: "http://localhost:8080"
  description: Generated server url
paths:
  /Books:
    get:
      tags:
      - book-resource
      operationId: retrieveAllBooks
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    post:
      tags:
      - book-resource
      operationId: createBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: object
  /Books/{id}:
    get:
      tags:
      - book-resource
      operationId: retrieveBook
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Book"
    put:
      tags:
      - book-resource
      operationId: updateBook
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - book-resource
      operationId: deleteBook
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: default response
  /CheckOut:
    post:
      tags:
      - book-resource
      operationId: checkout
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TotalCost"
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        author:
          type: string
        type:
          type: string
        classification:
          type: string
        price:
          type: number
          format: double
        isbn:
          type: string
    Order:
      type: object
      properties:
        bookIds:
          type: array
          items:
            type: integer
            format: int64
        promoCode:
          type: string
    TotalCost:
      type: object
      properties:
        totalCost:
          type: number
          format: double
